using Microsoft.EntityFrameworkCore;
using bagAPI.Models;

namespace bagAPI.Data
{
    public class bagAPIContext : DbContext
    {
        public bagAPIContext(DbContextOptions<bagAPIContext> options)
            : base(options)
        { }

        public DbSet<Toy> Toy { get; set; }
        public DbSet<Child> Child { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // If a model has a date field that should be generated by the database
        }
    }
}
